# Generated by Django 4.1.6 on 2023-02-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_preview_alter_recipe_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.CharField(default='', max_length=250),
        ),
    ]
